### PR TITLE
Properly re-throw exceptions in submitTxNami

### LINKED ISSUE #218: Adjust error-handling for submitting tx in `Wallet` FFI module
Not sure if there has been a breaking change with Nami, but submission failures apparently don't always throw an exception but instead return an object describing the failure. For example:
```js
{
    "code": 2,
    "info": "Wallet could not send the tx.",
    "message": "..."
}
```
So we need to check for this as well as catching actual exceptions

### PR DESCRIPTION
**Pull request by adamczykm**
Closes #218

### CODE REVIEW

**Comment by adamczykm** [comment]
Created a new one branched out of the current master.

File: src/Wallet.js [hunk 1]
```diff
@@ -4,27 +4,26 @@
...
-    return nami.submitTx(txHex);
-  } catch (e) {
-      console.log(e);
-      throw(e);
-  }
+exports._submitTxNami = txHex => nami => () => {
+  return nami.submitTx(txHex)
+      .catch(e => {
+          console.log("Error in submitTxNami: ", e);
+          throw (JSON.stringify(e));
```
Comment (klntsky) [inline src/Wallet.js:27]: parentheses are optional after throw.

**Review by klntsky — APPROVED** [review]

**Review by ngua — APPROVED** [review]
